-- Paste this into your Supabase SQL Editor and run it!

CREATE TABLE IF NOT EXISTS public.parse_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    source text not null,
    input_text text not null,
    result_json jsonb not null,
    user_id uuid null -- Ready for Step 2!
);

-- Set up Row Level Security (optional but recommended for the future)
ALTER TABLE public.parse_history ENABLE ROW LEVEL SECURITY;

-- Allow anon inserts for now (since we don't have Auth setup yet)
CREATE POLICY "Allow anon insert" ON public.parse_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon select" ON public.parse_history FOR SELECT USING (true);

-- Adding Subscription Tier for Basic/Pro Packages
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS subscription_tier text default 'basic';
